# DigitalOcean App Platform Specification
# Deploy: doctl apps create --spec .do/app.yaml

name: iconsai-backend
region: nyc

services:
  - name: api
    github:
      repo: iconsai/iconsai-backend
      branch: main
      deploy_on_push: true
    dockerfile_path: Dockerfile
    http_port: 8000
    instance_count: 1
    instance_size_slug: basic-xxs
    health_check:
      http_path: /health
      initial_delay_seconds: 10
      period_seconds: 30
    envs:
      - key: OPENAI_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: ELEVENLABS_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: ELEVENLABS_VOICE_ID
        scope: RUN_TIME
        value: "21m00Tcm4TlvDq8ikWAM"
      - key: ELEVENLABS_MODEL_ID
        scope: RUN_TIME
        value: "eleven_turbo_v2_5"
      - key: TTS_PROVIDER
        scope: RUN_TIME
        value: "elevenlabs"
      - key: CORS_ORIGINS
        scope: RUN_TIME
        value: "https://app.iconsai.com.br,https://core.iconsai.ai,https://iconsai.com.br,http://localhost:5173"
      - key: LOG_LEVEL
        scope: RUN_TIME
        value: "INFO"
      - key: PORT
        scope: RUN_TIME
        value: "8000"
